# TÍTULO DESCRITIVO.
# Direitos autorais (C) ANO DO TITULAR DOS DIREITOS AUTORAIS DO PACOTE
# Este arquivo é distribuído sob a mesma licença do pacote PACOTE.
# PRIMEIRO AUTOR <EMAIL@ENDERECO>, ANO.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-10-24 19:17+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: settings/settings/common.py:106
msgid "english"
msgstr "Inglês"

#: settings/settings/common.py:107
#, fuzzy
#| msgid "Portuguese"
msgid "portuguese"
msgstr "português"

#: users/views.py:64
msgid "invalid-password"
msgstr ""

#: users/views.py:77
msgid "password-updated-successfully"
msgstr "Senha atualizada com sucesso"

#: users/views.py:94
msgid "user-not-found"
msgstr ""

#: users/views.py:126
#, fuzzy
#| msgid "Could not find a user to activate"
msgid "no-user-to-activate"
msgstr "Não foi possível encontrar um usuário para ativar"

#: users/views.py:160 users/views.py:224
msgid "invalid-email-password"
msgstr "E-mail ou senha inválidos"

#: users/views.py:169
msgid "cant-create-user"
msgstr "Falha ao criar usuário"

#: users/views.py:196
msgid "user-created-successfully"
msgstr "Usuário criado com sucesso."

#: users/views.py:215
msgid "incomplete-credentials"
msgstr "Credenciais inválidas."

#: users/views.py:226
msgid "invalid-credentials"
msgstr "Credenciais inválidas."

#: users/views.py:234
msgid "logged-in-successfully"
msgstr "Usuário criado com sucesso."

#: users/views.py:287
msgid "say_hello"
msgstr "Olá!"

#~ msgid "Could not find a user to activate"
#~ msgstr "Não foi possível encontrar um usuário para ativar"

#~ msgid "Email sent."
#~ msgstr "E-mail enviado."

#~ msgid "Account successfully activated."
#~ msgstr "Conta ativada com sucesso."
